use_frameworks!

platform :ios, '9.0'

target 'OldedDemoViewModel_Example' do
  pod 'OldedDemoViewModel', :path => '../'

  target 'OldedDemoViewModel_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
