use_frameworks!

platform :ios, '10.0'

target 'OldedDemoViewModel_Example' do
  pod 'OldedDemoViewModel', :path => '../'
  pod 'NHNewDemoProtocolManager'
  pod 'NHNewDemoViewModelProtocol'

  target 'OldedDemoViewModel_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
